name: Auto PR from feature/* to dev

on:
  push:
    branches:
      - "feature/**"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  open-or-update-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure GitHub CLI is available
        run: gh --version

      - name: Create or update PR into dev
        env:
          GH_TOKEN: ${{ secrets.PAT }}  # or use secrets.PAT with repo scope if needed
        run: |
          set -e
          BASE="dev"
          HEAD="${GITHUB_REF_NAME}"
          TITLE="Automated PR for ${HEAD}"
          BODY="Auto PR from **${HEAD}** to **${BASE}**."

          # Find existing open PR from HEAD -> BASE
          PR_NUMBER=$(gh pr list \
            --state open \
            --head "$HEAD" \
            --base "$BASE" \
            --json number \
            --jq '.[0].number' || true)

          if [ -n "$PR_NUMBER" ]; then
            echo "PR #$PR_NUMBER already exists. Updating title/body."
            gh pr edit "$PR_NUMBER" --title "$TITLE" --body "$BODY"
          else
            echo "Creating new PR from ${HEAD} to ${BASE}"
            gh pr create --base "$BASE" --head "$HEAD" --title "$TITLE" --body "$BODY" --draft=false
